#!/usr/bin/env bash
# regen-plugins-manifest.sh — generate a static plugins manifest from a
# package.json, so a bundler can see workspace plugins that would
# otherwise hide behind `await import(<var>)` call sites.
#
# Usage:
#   ./scripts/regen-plugins-manifest.sh <package.json> [--pattern <glob>] [--out <ts-path>]
#
# Example (the edorer pattern that hit Tier 1):
#   ./scripts/regen-plugins-manifest.sh services/user-api/package.json \
#       --pattern '@edorer-plugin/*' \
#       --out services/user-api/src/plugins.generated.ts
#
# Behavior:
#   - Reads `dependencies` from <package.json>.
#   - Filters by --pattern (supports `*` glob, `prefix/*`, exact names).
#     If unset, matches any dep whose version starts with `workspace:`.
#   - Writes a TypeScript module that exports:
#         export const plugins: Record<string, () => Promise<any>>
#     mapping each package name to a static `() => import("<pkg>")`.
#   - Output file path defaults to `<package.json dir>/src/plugins.generated.ts`.
#
# Why this exists:
#   Bundlers (esbuild, swc, bun) can only follow STATIC import strings.
#   A call site like `await import(row.package)` is unbundleable. A
#   static manifest with one entry per workspace package lets the
#   bundler see the whole graph; the call site changes from
#   `await import(row.package)` to `await plugins[row.package]()`.
#
# This script generates the manifest. The skill is allowed to write
# build metadata like this. Rewriting the call site is a separate,
# narrowly-scoped patch the orchestrator does in main.ts.

set -euo pipefail

PKG_JSON="${1:-}"
shift || true

if [[ -z "$PKG_JSON" || ! -f "$PKG_JSON" ]]; then
  cat >&2 <<USAGE
Usage: $0 <package.json> [--pattern <glob>] [--out <ts-path>]

Common patterns:
  --pattern '@edorer-plugin/*'      # everything under @edorer-plugin
  --pattern 'my-plugins/*'           # alt naming
  (omitted)                          # every dep whose version is "workspace:*"
USAGE
  exit 64
fi

PATTERN=""
OUT_PATH=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --pattern) PATTERN="$2"; shift 2 ;;
    --out)     OUT_PATH="$2"; shift 2 ;;
    *) echo "[regen-manifest] unknown flag: $1" >&2; exit 64 ;;
  esac
done

PKG_DIR="$(cd "$(dirname "$PKG_JSON")" && pwd)"
[[ -z "$OUT_PATH" ]] && OUT_PATH="$PKG_DIR/src/plugins.generated.ts"

# Ensure parent dir exists.
mkdir -p "$(dirname "$OUT_PATH")"

PATTERN="$PATTERN" PKG_JSON="$PKG_JSON" OUT_PATH="$OUT_PATH" python3 - <<'PY'
import fnmatch, json, os, sys

pkg = json.load(open(os.environ["PKG_JSON"]))
deps = {**(pkg.get("dependencies") or {}), **(pkg.get("devDependencies") or {})}

pattern = os.environ.get("PATTERN", "")
if pattern:
    matched = sorted(k for k in deps if fnmatch.fnmatch(k, pattern))
else:
    matched = sorted(
        k for k, v in deps.items()
        if isinstance(v, str) and v.startswith("workspace:")
    )

if not matched:
    sys.stderr.write(f"[regen-manifest] no deps matched pattern={pattern!r} or workspace:*\n")
    sys.exit(2)

lines = [
    "// auto-generated by glance-gate — do not edit.",
    "//",
    "// Static manifest of plugin packages so a bundler can see them as",
    "// static imports. Regenerate with scripts/regen-plugins-manifest.sh",
    "// whenever a new plugin package is added to package.json.",
    "",
    "export type PluginModule = {",
    "  default?: any;",
    "  [key: string]: any;",
    "};",
    "",
    "export const plugins: Record<string, () => Promise<PluginModule>> = {",
]
for name in matched:
    n = json.dumps(name)
    lines.append(f"  {n}: () => import({n}),")
lines.append("};")
lines.append("")

with open(os.environ["OUT_PATH"], "w") as f:
    f.write("\n".join(lines))

print(f"[regen-manifest] wrote {len(matched)} entries to {os.environ['OUT_PATH']}")
PY
